### ISSUE TITLE
Feedback Request: LNX 8

### ISSUE THREAD

**Issue by sait125** [Techgrounds-Cloud-9/cloud-9-sait125#2]
**Feedback Request [SUBJECT]**
Permalink to file: [LINK]

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by jeenlearn** [comment]
**Summary**
- Does the summary describe the subject matter fully?Yes
- Is the summary written in own words?Yes
- Is there crucial information missing in the summary?No
- Is the description clear enough?Yes

**Key Terminology**
- Are there missing key terms? No
- Are the key terms explained well?Yes

**Sources**
- Are the sources mentioned?Yes
- Are the mentioned sources correct?Yes

**Excercise**
(Where applicable)
- Is the result correct? Yes
- Are the experienced problems and solutions described well?Yes

**Comment by jairvaneer** [comment]
**Summary**
- Does the summary describe the subject matter fully?
- Yes
- Is the summary written in own words?
- Yes
- Is there crucial information missing in the summary?
- No
- Is the description clear enough?
- Yes

**Key Terminology**
- Are there missing key terms?
- No
- Are the key terms explained well?
- Yes

**Sources**
- Are the sources mentioned?
- Yes
- Are the mentioned sources correct?
- Yes

**Excercise**
(Where applicable)
- Is the result correct?
- Yes
- Are the experienced problems and solutions described well?
- Yes
